version: 0.2

phases:
  install:
    runtime-versions:
      python: 10 # Example runtime (you can specify the version of your environment, e.g., python, nodejs, etc.)
    commands:
      - echo Installing dependencies...
      - pip install pandas
  
  pre_build:
    commands:
      - echo Running pre-build commands...
      #TESTING

  build:
    commands:
      - echo Building the project...

  post_build:
    commands:
      - echo Build completed.
      #- echo Running post-build commands...
      #- aws s3 cp ./build s3://your-s3-bucket-name --recursive # Example: Upload build artifacts to S3.
      - echo Deploying or running any additional scripts...

artifacts:
  files:
    - '**/*' # Example: Include all files in the build output directory.
  base-directory: build # Example: Specify the base directory where your build output resides.
  discard-paths: yes # Example: Discard the folder structure when copying files.

env:
  variables:
    ENVIRONMENT: "dev" # Example environment variable. Add more as needed.
    S3_BUCKET: "your-s3-bucket-name"
