version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.10
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y make docker-compose docker.io
      - touch .env
  
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 257743355435.dkr.ecr.eu-west-2.amazonaws.com

  build:
    commands:
      - make build

  post_build:
    commands:
      - docker tag docker.io/library/src_frontend:latest 257743355435.dkr.ecr.eu-west-2.amazonaws.com/nasa_frontend:latest
      - docker push 257743355435.dkr.ecr.eu-west-2.amazonaws.com/nasa_frontend:latest
      - docker tag docker.io/library/src_backend:latest 257743355435.dkr.ecr.eu-west-2.amazonaws.com/nasa_backend:latest
      - docker push 257743355435.dkr.ecr.eu-west-2.amazonaws.com/nasa_backend:latest