version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend 
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_LOAD_BALANCER_URL
      - BACKEND_WEBSOCKET_URL
      - ENVIRONMENT
      - REDIRECT_URI
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_ROOT_PASSWORD
      - OPENAI_API_KEY
      - DB_USER
      - DB_HOSTNAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - mysql
    command: ["/bin/sh", "-c", "sleep 5 && python mysql_database/schema.py && poetry run uvicorn app:app --host 0.0.0.0 --port 5000 --reload"]

  qdrant:
    image: qdrant/qdrant:v1.12.1
    ports:
      - "6333:6333"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
