apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
data:
  BACKEND_LOAD_BALANCER_URL: YTFhZjI2NjRiYjU5YTQ5OTBhODkyOWE0ZDBiNGQ4YzctMzEzMTc0MjQuZXUtd2VzdC0yLmVsYi5hbWF6b25hd3MuY29t
  BACKEND_WEBSOCKET_URL: YTFhZjI2NjRiYjU5YTQ5OTBhODkyOWE0ZDBiNGQ4YzctMzEzMTc0MjQuZXUtd2VzdC0yLmVsYi5hbWF6b25hd3MuY29t
  ENVIRONMENT: REVWRUxPUE1FTlQ=
  REDIRECT_URI: bG9jYWxob3N0OjgwMDA=