apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  serviceAccountName: frontend-service-account
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 257743355435.dkr.ecr.eu-west-2.amazonaws.com/nasa_frontend:latest